namespace EmulatorPCHub.Core;

/// <summary>Deutsch → Englisch (Teil 2: Controller-Seiten).</summary>
internal static partial class Entries
{
    private static void AddControllers(Action<string, string> A)
    {
        // ── Tastenbelegung / Diagramme ─────────────────────────────
        A("Dein Controller (PS5)", "Your controller (PS5)"); A("Deine Wii Remote + Nunchuk", "Your Wii Remote + Nunchuk");
        A("Im Spiel: Wii Remote + Nunchuk", "In game: Wii Remote + Nunchuk"); A("Im Spiel: GameCube-Controller", "In game: GameCube controller");
        A("Im Spiel: Wii U Pro Controller – dieselben Tasten wie am GamePad", "In game: Wii U Pro Controller – same buttons as the GamePad");
        A("Im Spiel: Wii U GamePad", "In game: Wii U GamePad"); A("Im Spiel: Switch Pro Controller", "In game: Switch Pro Controller");
        A("Wii-Taste", "Wii button"); A("Funktion in diesem Spiel", "Function in this game");
        A("Im Spiel nicht belegt: ", "Unused in game: ");
        A("Echte Wii Remote: Die Tasten sind fest. Mit A trägst du ein, was sie im Spiel machen.", "Real Wii Remote: the buttons are fixed. Press A to note what they do in the game.");
        A("Mit A auf einer Zeile legst du eine andere Taste fest (belegte Tasten werden getauscht)", "Press A on a row to choose a different button (assigned buttons are swapped)");
        A(" und trägst ein, was sie im Spiel macht.", " and note what it does in the game.");
        A(" Kursiv = Vorschlag des Spiels.", " Italic = suggestion for the game.");
        A(" Hinweis: Umbelegungen gelten für Controller, nicht für die Tastatur.", " Note: remapping applies to controllers, not the keyboard.");
        A("Alle Tasten zurücksetzen", "Reset all buttons"); A("Standardbelegung wiederhergestellt", "Default mapping restored");
        A("Xbox-Taste", "Xbox button"); A("Deine Taste", "Your button"); A("PS5-Taste", "PS5 button"); A("— nicht belegt", "— unassigned");
        A("Sticks sind fest belegt und lassen sich nicht auf Tasten legen.", "Sticks are fixed and cannot be mapped to buttons.");
        A("Keine (nicht belegen)", "None (unassigned)");
        A("Ist die gewählte Taste schon belegt, werden die beiden Tasten getauscht.", "If the chosen button is already assigned, the two buttons are swapped.");
        A("z. B. Springen, Angreifen, Item benutzen … (leer = nicht genutzt)", "e.g. jump, attack, use item … (empty = unused)");
        A("Zurücksetzen", "Reset");
        A("Belegung gespeichert – gilt ab dem nächsten Spielstart", "Mapping saved – applies from the next game launch");
        A("Abgeleitet aus Plattform, Emulator und Spielart – nicht jedes Spiel ist einzeln getestet.", "Derived from platform, emulator and game type – not every game has been tested individually.");
        A("Empfohlen", "Recommended"); A("Geht", "Works"); A("Eingeschränkt", "Limited"); A("Geht nicht", "Not supported");
        A("Wii Remote schütteln", "Shake Wii Remote"); A("Zeiger (auf den Bildschirm zeigen)", "Pointer (aim at the screen)"); A("Zeiger", "Pointer");
        A("Steuerkreuz ↑", "D-pad ↑"); A("Steuerkreuz ↓", "D-pad ↓"); A("Steuerkreuz ←", "D-pad ←"); A("Steuerkreuz →", "D-pad →");
        A("Unterseite", "Underside"); A("Nunchuk schütteln", "Shake Nunchuk"); A("Nunchuk-Stick", "Nunchuk stick");
        A("Control-Stick", "Control stick"); A("Control-Stick langsam", "Control stick (slow)"); A("Start/Pause", "Start/Pause");
        A("Bildschirm (Touch = Maus)", "Screen (touch = mouse)"); A("Linker Stick", "Left stick"); A("Linken Stick drücken", "Press left stick");
        A("Rechter Stick", "Right stick"); A("Rechten Stick drücken", "Press right stick");
        A("Blau", "Blue"); A("Rot", "Red"); A("Grün", "Green"); A("Pink", "Pink");
        A("Xbox-Logo leuchtet weiß (keine Spieler-LED)", "Xbox logo glows white (no player LED)"); A("keine Spieler-LED", "no player LED");
        A("Kamerabild der Wii Remote – die Sensorleiste erscheint als 2 helle Punkte", "Wii Remote camera view – the sensor bar appears as 2 bright dots");
        A("Zeiger auf dem Bildschirm", "Pointer on screen"); A("Warte auf Daten der Wii Remote …", "Waiting for Wii Remote data …");
        A("Wii Remote eingeschaltet und verbunden? Eine Taste drücken.", "Is the Wii Remote on and connected? Press a button.");
        A("✗ Keine Sensorpunkte sichtbar", "✗ No sensor dots visible");
        A("Wii Remote auf die Leiste richten (1–3 m Abstand). Bleibt es leer: Leiste hat keinen Strom (USB/Netz) oder steht verdeckt.", "Point the Wii Remote at the bar (1–3 m distance). If it stays empty: the bar has no power (USB/mains) or is covered.");
        A("! Nur 1 Punkt sichtbar", "! Only 1 dot visible");
        A("Ein Ende der Leiste ist verdeckt oder außerhalb des Blickfelds – etwas weiter weg gehen bzw. gerader zielen.", "One end of the bar is covered or outside the field of view – move further away or aim more directly.");
        A("✓ Sensorleiste funktioniert", "✓ Sensor bar works");
        A("Neben der Leiste sieht die Kamera weitere IR-Quellen (Sonne, Kerzen, Halogenlampen, Spiegelungen). Diese abschirmen.", "Besides the bar, the camera sees other IR sources (sun, candles, halogen lamps, reflections). Shield them.");
        A("Gedrückt: ", "Pressed: "); A("Tasten: keine gedrückt (zum Testen drücken)", "Buttons: none pressed (press to test)");

        // ── Controller-Profil ──────────────────────────────────────
        A("Controller – Standardprofil", "Controllers – default profile");
        A("Gilt für alle Spiele ohne eigenes Profil.", "Applies to all games without their own profile.");
        A("Eigenes Profil für dieses Spiel anlegen", "Create own profile for this game");
        A("PadForge-Profil (leer = „EmulatorPCHub“)", "PadForge profile (empty = “EmulatorPCHub”)");
        A("Tastenbelegung in den Emulatoren automatisch setzen", "Set button mapping in the emulators automatically");
        A("Vibration", "Rumble");
        A("Ist die automatische Belegung aus, übergibt der Hub nur die Spielerreihenfolge nicht – du verwaltest die Belegung dann im Emulator selbst (Advanced).", "With automatic mapping off, the hub does not pass on the player order – you manage the mapping in the emulator yourself (advanced).");
        A("Eigenes Profil löschen (Standard verwenden)", "Delete own profile (use default)");
        A("Fest: Tastatur", "Fixed: keyboard"); A("Fest: Gerät nicht verbunden", "Fixed: device not connected");
        A(" (keinem Spieler zugewiesen)", " (not assigned to a player)"); A("Nativ", "Native"); A("Gerät wählen …", "Choose device …");
        A("Fest zugeordnete Geräte gelten nur für dieses Profil. Ein Gerät bekommt nie zwei Spieler – ", "Fixed devices apply to this profile only. A device never gets two players – ");
        A("ist es schon vergeben, rückt das nächste freie Gerät nach.", "if it is already taken, the next free device moves up.");
        A("Tastenbelegung", "Button mapping");
        A("WiiCompiled ist ein PC-Port mit eigener Belegung – die Tasten stellst du im Spiel mit F10 ein.", "WiiCompiled is a PC port with its own mapping – set the buttons in the game with F10.");
        A(" (Tastatur – Tastennamen siehe Controller-Seite, hier im PS5-Schema)", " (keyboard – key names see Controllers page, shown here in PS5 layout)");
        A("  ·  Automatische Belegung ist aus: Der Emulator nutzt deine eigene Belegung, die Tabelle zeigt die Hub-Belegung.", "  ·  Automatic mapping is off: the emulator uses your own mapping, the table shows the hub mapping.");
        A("So startet das Spiel", "How the game starts"); A("Kein Controller und keine Tastatur zugeordnet", "No controller and no keyboard assigned");
        A("über PadForge", "via PadForge");
        A("WiiCompiled übernimmt SDL-Controller direkt; die Feinbelegung erfolgt im Spiel mit F10.", "WiiCompiled takes SDL controllers directly; fine mapping is done in the game with F10.");
        A("GameCube-Controller", "GameCube controller"); A("Wii U Pro Controller", "Wii U Pro Controller");
        A("Joy-Con-Paar", "Joy-Con pair");

        // ── Controller-Seite ───────────────────────────────────────
        A("Beitreten: Drücke A (bzw. ✕) auf jedem Controller – in der Reihenfolge Spieler 1, 2, 3, 4.", "Join: press A (or ✕) on each controller – in the order player 1, 2, 3, 4.");
        A("Spieler", "Players"); A("Wer mit welchem Controller spielt – und was am Controller leuchtet.", "Who plays with which controller – and what lights up on the controller.");
        A("Neu zuordnen (Beitreten)", "Reassign (join)"); A("Automatisch sortieren", "Sort automatically"); A("Vibration testen", "Test rumble");
        A("Nicht zugewiesen", "Not assigned"); A("Verbunden, aber noch keinem Spieler zugeordnet.", "Connected, but not assigned to a player yet.");
        A("Spieler zuweisen", "Assign player"); A("Identifizieren", "Identify"); A("Tastatur in Spielen", "Keyboard in games");
        A("Welchen Spielerplatz die Tastatur in Spielen bekommt.", "Which player slot the keyboard gets in games.");
        A("Spieler 1", "Player 1"); A("Spieler 2", "Player 2"); A("Spieler 3", "Player 3"); A("Spieler 4", "Player 4");
        A("Automatisch = Tastatur ist Spieler 1, wenn kein Controller angeschlossen ist.", "Automatic = the keyboard is player 1 when no controller is connected.");
        A("Belegung in allen Emulatoren gleich: Stick W/A/S/D · A=Z · B=X · X=C · Y=V · L=E · R=U · ZL=Q · ZR=O · ", "Same mapping in all emulators: stick W/A/S/D · A=Z · B=X · X=C · Y=V · L=E · R=U · ZL=Q · ZR=O · ");
        A("+ = Enter · D-Pad = Pfeiltasten · rechter Stick I/J/K/L.", "+ = Enter · D-pad = arrow keys · right stick I/J/K/L.");
        A("Stick W/A/S/D · A=Z · B=X · X=C · Y=V · L=E · R=U · ZL=Q · ZR=O · + = Enter · D-Pad = Pfeiltasten · rechter Stick I/J/K/L.", "Stick W/A/S/D · A=Z · B=X · X=C · Y=V · L=E · R=U · ZL=Q · ZR=O · + = Enter · D-pad = arrow keys · right stick I/J/K/L.");
        A("Tastenbelegung & Profil pro Spiel", "Button mapping & profile per game");
        A("Pro Spiel: welche Taste welche Konsolen-Taste ist und was sie dort macht. Der Hub schreibt die Belegung beim Start selbst in den Emulator.", "Per game: which button is which console button and what it does there. The hub writes the mapping into the emulator at launch.");
        A("Standardprofil (alle Spiele)", "Default profile (all games)"); A("Kompatibilitätsschicht (PadForge)", "Compatibility layer (PadForge)");
        A("Nur für Controller, die ein Emulator nicht selbst kennt – z. B. eine Wii Remote im Switch-Emulator.", "Only for controllers an emulator does not know itself – e.g. a Wii Remote in the Switch emulator.");
        A("PadForge nicht installiert (Komponenten → PadForge)", "PadForge not installed (Components → PadForge)");
        A("Ersteinrichtung erledigt", "Initial setup done");
        A("Ersteinrichtung nötig (installiert den Treiber HIDMaestro, fragt einmal nach Admin-Rechten)", "Initial setup required (installs the HIDMaestro driver, asks for admin rights once)");
        A("Läuft im Hintergrund", "Running in the background"); A("Wird bei Bedarf automatisch gestartet", "Started automatically when needed");
        A("Profilsteuerung durch den Hub aktiv", "Profile control by the hub active"); A("Profilsteuerung wird beim Start eingeschaltet", "Profile control is switched on at launch");
        A("PadForge automatisch verwenden, wenn ein Spiel einen Controller nicht direkt unterstützt", "Use PadForge automatically when a game does not support a controller directly");
        A("Xbox-Controller laufen immer nativ. Sony- und Nintendo-Controller gehen nur dann über PadForge (virtueller Xbox-Controller), ", "Xbox controllers always run natively. Sony and Nintendo controllers only go through PadForge (virtual Xbox controller) ");
        A("wenn der Emulator sie nicht selbst unterstützt.", "if the emulator does not support them itself.");
        A("PadForge starten", "Start PadForge"); A("PadForge einrichten", "Set up PadForge"); A("PadForge öffnen (Advanced)", "Open PadForge (advanced)");
        A("Zu Komponenten", "Go to Components"); A("Anleitungen", "Guides"); A("Verbinden und Einrichten – zum Aufklappen.", "Connect and set up – click to expand.");
        A("PS5-Controller (DualSense)", "PS5 controller (DualSense)"); A("Kabel: per USB-C anstecken – fertig.", "Cable: plug in via USB-C – done.");
        A("Bluetooth: PS-Taste + Create ca. 3 s halten, bis die Lichtleiste schnell blinkt → Windows: Bluetooth → Gerät hinzufügen → „DualSense Wireless Controller“.", "Bluetooth: hold PS button + Create for about 3 s until the light bar blinks quickly → Windows: Bluetooth → Add device → “DualSense Wireless Controller”.");
        A("Im Hub: ✕ = bestätigen, ○ = zurück. Im Spiel gilt die Tabelle unter „Tastenbelegung“ des Spiels.", "In the hub: ✕ = confirm, ○ = back. In a game the table under the game's “Button mapping” applies.");
        A("Bewegungssteuerung (Gyro) nutzen Cemu und Eden automatisch über SDL, z. B. zum Zielen.", "Cemu and Eden use motion controls (gyro) automatically via SDL, e.g. for aiming.");
        A("Xbox-Controller", "Xbox controller");
        A("Kabel oder Bluetooth (Pair-Taste oben am Controller halten, bis das Xbox-Logo schnell blinkt → Windows: Gerät hinzufügen).", "Cable or Bluetooth (hold the pair button on top of the controller until the Xbox logo blinks quickly → Windows: Add device).");
        A("Läuft in allen Emulatoren direkt (XInput), die Belegung entspricht dem PS5-Controller nach Position.", "Works directly in all emulators (XInput); the mapping matches the PS5 controller by position.");
        A("Switch Pro Controller / Joy-Con", "Switch Pro Controller / Joy-Con");
        A("Sync-Knopf oben neben dem USB-C-Anschluss halten, bis die LEDs laufen → Windows: Gerät hinzufügen → „Pro Controller“. Alternativ per USB-Kabel.", "Hold the sync button next to the USB-C port until the LEDs run → Windows: Add device → “Pro Controller”. Or use a USB cable.");
        A("Joy-Con einzeln koppeln (Sync-Knopf an der Schiene); der Hub erkennt sie als Joy-Con-Paar für Switch-Spiele.", "Pair each Joy-Con individually (sync button on the rail); the hub recognizes them as a Joy-Con pair for Switch games.");
        A("Tasten gelten nach der Nintendo-Beschriftung: A rechts, B unten.", "Buttons follow the Nintendo labels: A on the right, B at the bottom.");
        A("Wii Remote mit der DolphinBar verbinden", "Connect a Wii Remote with the DolphinBar");
        A("DolphinBar per USB direkt am PC anschließen und mittig über (oder unter) den Bildschirm legen.", "Connect the DolphinBar via USB directly to the PC and place it centered above (or below) the screen.");
        A("Mode 4 einstellen: die Mode-Taste an der DolphinBar drücken, bis die blaue LED bei „4“ leuchtet. Oben muss „Mode 4 (Dolphin)“ mit ✓ stehen.", "Set mode 4: press the mode button on the DolphinBar until the blue LED at “4” lights up. “Mode 4 (Dolphin)” with ✓ must appear above.");
        A("Wii Remote einschalten: 1 und 2 gleichzeitig drücken. Die LEDs blinken, dann erscheint sie hier unter „Wii-Remote-Verbindungen“ in Slot 1 – ", "Turn on the Wii Remote: press 1 and 2 at the same time. The LEDs blink, then it appears here under “Wii Remote connections” in slot 1 – ");
        A("die nächste Wii Remote in Slot 2 usw. Beim ersten Mal ggf. stattdessen den roten Sync-Knopf unter dem Batteriedeckel drücken.", "the next Wii Remote in slot 2 and so on. The first time you may need to press the red sync button under the battery cover instead.");
        A("Die LED zeigt den Spieler: LED 1 = Spieler 1 … LED 4 = Spieler 4. Ist die Tastatur Spieler 1, wird die erste Wii Remote Spieler 2 – ", "The LED shows the player: LED 1 = player 1 … LED 4 = player 4. If the keyboard is player 1, the first Wii Remote becomes player 2 – ");
        A("„Tastatur in Spielen“ auf „Aus“ stellen, wenn du nur mit Wii Remotes spielst.", "set “Keyboard in games” to “Off” if you only play with Wii Remotes.");
        A("„Identifizieren“ lässt eine Wii Remote kurz vibrieren; „Sensortest“ prüft Sensorleiste, Zeiger und Tasten.", "“Identify” makes a Wii Remote rumble briefly; “Sensor test” checks the sensor bar, pointer and buttons.");
        A("Nunchuk einfach einstecken – er erscheint als „Erweiterung: Nunchuk“. Später reicht zum Verbinden eine beliebige Taste bzw. 1+2.", "Just plug in the Nunchuk – it appears as “Extension: Nunchuk”. Later, any button or 1+2 is enough to connect.");
        A("Wii-Spiel im Hub starten – Dolphin übernimmt die Wii Remotes automatisch (keine Windows-Kopplung nötig). Ausschalten: Power-Taste 3 s halten.", "Start a Wii game in the hub – Dolphin takes over the Wii Remotes automatically (no Windows pairing needed). Turn off: hold the power button for 3 s.");
        A("Ohne DolphinBar: Windows → Bluetooth → Gerät hinzufügen → Bluetooth, roten Sync-Knopf drücken → „Nintendo RVL-CNT-01“ (PIN leer lassen). ", "Without DolphinBar: Windows → Bluetooth → Add device → Bluetooth, press the red sync button → “Nintendo RVL-CNT-01” (leave the PIN empty). ");
        A("Dein MediaTek-Bluetooth-Chip kann damit Probleme haben – die DolphinBar ist die zuverlässigere Lösung.", "Your MediaTek Bluetooth chip may have problems with this – the DolphinBar is the more reliable solution.");
        A("Wii-U-Spiele mit Wii Remote (Cemu): in Cemu unter Optionen → Eingabeeinstellungen einen Controller auf „Wiimote“ mit API „Wiimote“ stellen.", "Wii U games with Wii Remote (Cemu): in Cemu under Options → Input settings set a controller to “Wiimote” with API “Wiimote”.");
        A("Sensorleiste / DolphinBar", "Sensor bar / DolphinBar");
        A("Die Sensorleiste sendet nur Infrarotlicht – die Kamera in der Wii Remote sieht zwei Punkte und berechnet daraus den Zeiger. Die DolphinBar hat diese LEDs eingebaut.", "The sensor bar only emits infrared light – the camera in the Wii Remote sees two dots and calculates the pointer from them. The DolphinBar has these LEDs built in.");
        A("Mode 1–3 machen die Wii Remote zu Maus/Tastatur/Gamepad für Windows; für Dolphin und den Hub immer Mode 4.", "Modes 1–3 turn the Wii Remote into a mouse/keyboard/gamepad for Windows; always use mode 4 for Dolphin and the hub.");
        A("Sensortest: Bei 2 Punkten funktioniert alles. 0 Punkte = Leiste ohne Strom, verdeckt oder falsch gezielt. Mehr als 2 = Störlicht (Sonne, Kerzen, Halogen).", "Sensor test: with 2 dots everything works. 0 dots = bar without power, covered or wrongly aimed. More than 2 = interference (sun, candles, halogen).");
        A("Unter „Einstellungen“ die Position (über/unter dem Bildschirm) passend zur Lage wählen und bei zitterndem Zeiger die Empfindlichkeit senken.", "Under “Settings” choose the position (above/below the screen) to match your setup and lower the sensitivity if the pointer jitters.");
        A("Die originale Wii-Sensorleiste brauchst du mit DolphinBar nicht (ihr Stecker liefert nur Strom von der Wii).", "You do not need the original Wii sensor bar with a DolphinBar (its plug only gets power from the Wii).");
        A("Ohne Wii Remote zeigst du mit dem rechten Stick deines Controllers (Hub-Belegung).", "Without a Wii Remote you aim with the right stick of your controller (hub mapping).");
        A("Das echte GamePad funkt über ein eigenes WLAN-Protokoll und lässt sich unter Windows nicht verbinden.", "The real GamePad uses its own Wi-Fi protocol and cannot be connected under Windows.");
        A("Der Hub stellt deinen Controller in Wii-U-Spielen als Wii U Pro Controller ein – die Tasten sind dieselben wie am GamePad.", "The hub sets your controller up as a Wii U Pro Controller in Wii U games – the buttons are the same as on the GamePad.");
        A("GamePad-Bildschirm: in Cemu mit Strg+Tab einblenden, Touch-Eingaben mit der Maus.", "GamePad screen: show it in Cemu with Ctrl+Tab, touch input with the mouse.");
        A("Braucht ein Spiel zwingend das GamePad: im Controller-Profil des Spiels „Tastenbelegung automatisch setzen“ ausschalten und in Cemu Controller 1 auf „Wii U GamePad“ stellen.", "If a game strictly needs the GamePad: turn off “Set button mapping automatically” in the game's controller profile and set controller 1 in Cemu to “Wii U GamePad”.");
        A("Ohne Original-Controller: GameCube-Spiele belegt der Hub automatisch für PS5/Xbox (siehe Tastenbelegung im Spiel).", "Without an original controller: the hub maps GameCube games automatically for PS5/Xbox (see button mapping in the game).");
        A("Original-Controller: über den offiziellen Wii-U-GameCube-Adapter oder einen Mayflash-Adapter (Schalter auf „Wii U“).", "Original controllers: via the official Wii U GameCube adapter or a Mayflash adapter (switch set to “Wii U”).");
        A("Einmalig den Treiber mit Zadig installieren: Gerät „WUP-028“ wählen → WinUSB → Install.", "Install the driver once with Zadig: choose device “WUP-028” → WinUSB → Install.");
        A("In Dolphin unter Controller den Port auf „GameCube-Adapter für Wii U“ stellen und im Controller-Profil des Spiels „Tastenbelegung automatisch setzen“ ausschalten.", "In Dolphin under Controllers set the port to “GameCube Adapter for Wii U” and turn off “Set button mapping automatically” in the game's controller profile.");
        A("Wer die Tastatur bekommt, stellst du oben unter „Tastatur in Spielen“ ein.", "Who gets the keyboard is set above under “Keyboard in games”.");
        A("Texteingaben: In Wii-Spielen mit USB-Tastatur-Unterstützung, in Cemu und Eden tippst du direkt mit der PC-Tastatur.", "Text input: in Wii games with USB keyboard support, in Cemu and in Eden you type directly with the PC keyboard.");
        A("Nintendo DS / 3DS (melonDS, Azahar)", "Nintendo DS / 3DS (melonDS, Azahar)");
        A("Der Hub belegt Spieler 1 automatisch nach Position: rechte Taste = A, untere = B, obere = X, linke = Y, L1/R1 = L/R; beim 3DS zusätzlich L2/R2 = ZL/ZR, linker Stick = Circle Pad, rechter Stick = C-Stick.", "The hub maps player 1 automatically by position: right button = A, bottom = B, top = X, left = Y, L1/R1 = L/R; on 3DS additionally L2/R2 = ZL/ZR, left stick = Circle Pad, right stick = C-Stick.");
        A("DS: Das Steuerkreuz liegt zusätzlich auf dem linken Stick. Tastatur in melonDS: A=X · B=Z · X=S · Y=A · L=Q · R=W · Start=Enter · Select=Rücktaste · Steuerkreuz = Pfeiltasten.", "DS: the D-pad is additionally on the left stick. Keyboard in melonDS: A=X · B=Z · X=S · Y=A · L=Q · R=W · Start=Enter · Select=Backspace · D-pad = arrow keys.");
        A("Den unteren Bildschirm (Touchscreen) bedienst du in beiden Emulatoren mit der Maus.", "You operate the lower screen (touchscreen) with the mouse in both emulators.");
        A("DS und 3DS haben nur einen Spieler – weitere Controller im Profil werden ignoriert.", "DS and 3DS have only one player – further controllers in the profile are ignored.");
        A("3DS-Spiele als .3ds/.cci/.cxi (oder komprimiert .z3ds) ablegen; .cia-Dateien zuerst in Azahar über „Datei → CIA installieren“ einspielen.", "Put 3DS games as .3ds/.cci/.cxi (or compressed .z3ds); install .cia files first in Azahar via “File → Install CIA”.");
        A("Bedienung im Hub", "Using the hub");
        A("D-Pad / Stick = Navigation   ·   A = bestätigen   ·   B = zurück   ·   X/Y = Schnellaktionen", "D-pad / stick = navigate   ·   A = confirm   ·   B = back   ·   X/Y = quick actions");
        A("Start/+ = Optionen   ·   Home/Guide = Hub-Menü   ·   Home + Minus (1,5 s) = laufendes Spiel beenden (Xbox/XInput)", "Start/+ = options   ·   Home/Guide = hub menu   ·   Home + Minus (1.5 s) = quit running game (Xbox/XInput)");
        A("A/B richten sich nach der Beschriftung des Controllers: Bei Nintendo-Controllern ist A rechts, bei PlayStation ✕ = bestätigen.", "A/B follow the controller's labels: on Nintendo controllers A is on the right, on PlayStation ✕ = confirm.");
        A("A/B tauschen", "Swap A/B"); A("Bestätigen und Abbrechen in Spielen", "Confirm and cancel in games");
        A("Bei PlayStation- und Xbox-Controllern: ✕ / A (untere Taste) = bestätigen, ○ / B (rechte Taste) = zurück.", "On PlayStation and Xbox controllers: ✕ / A (bottom button) = confirm, ○ / B (right button) = back.");
        A("Gilt für Wii-U-, Switch-, DS- und 3DS-Spiele in allen Emulatoren (Wii und GameCube bestätigen ohnehin mit ✕). ", "Applies to Wii U, Switch, DS and 3DS games in all emulators (Wii and GameCube confirm with ✕ anyway). ");
        A("Ausgeschaltet wird wie auf Nintendo-Konsolen nach Position belegt (rechte Taste = A). Nintendo-Controller bleiben unverändert.", "When off, it is mapped by position like on Nintendo consoles (right button = A). Nintendo controllers stay unchanged.");
        A("Bestätigen mit ✕ (untere Taste)", "Confirm with ✕ (bottom button)");
        A("DolphinBar & Wii Remotes", "DolphinBar & Wii Remotes");
        A("Status der Sensorleiste, verbundene Wii Remotes, Sensortest und Einstellungen.", "Sensor bar status, connected Wii Remotes, sensor test and settings.");
        A("Suche DolphinBar und Wii Remotes …", "Searching for DolphinBar and Wii Remotes …");
        A("DolphinBar erkannt – Mode 4 (Dolphin) · bereit für Wii-Spiele", "DolphinBar detected – mode 4 (Dolphin) · ready for Wii games");
        A("DolphinBar erkannt, steht aber auf Mode 3 (Gamepad). Für Wii-Spiele und den Sensortest ", "DolphinBar detected but set to mode 3 (gamepad). For Wii games and the sensor test ");
        A("die Mode-Taste an der Leiste drücken, bis die blaue LED bei „4“ leuchtet.", "press the mode button on the bar until the blue LED at “4” lights up.");
        A("DolphinBar erkannt, steht aber auf Mode 1/2 (Maus/Tastatur). Mode-Taste drücken, ", "DolphinBar detected but set to mode 1/2 (mouse/keyboard). Press the mode button ");
        A("bis die blaue LED bei „4“ leuchtet.", "until the blue LED at “4” lights up.");
        A("Keine DolphinBar angeschlossen – Wii Remotes laufen über Windows-Bluetooth", "No DolphinBar connected – Wii Remotes run via Windows Bluetooth");
        A("Keine DolphinBar gefunden – USB-Kabel prüfen (am besten direkt am PC, nicht am USB-Hub)", "No DolphinBar found – check the USB cable (ideally directly at the PC, not a USB hub)");
        A("Sensorleiste: Die Infrarot-LEDs der DolphinBar leuchten, solange sie USB-Strom hat. ", "Sensor bar: the DolphinBar's infrared LEDs are lit as long as it has USB power. ");
        A("Ob die Wii Remote sie sieht, zeigt der Sensortest unten.", "The sensor test below shows whether the Wii Remote sees them.");
        A("Anleitung", "Guide"); A("Wii-Remote-Verbindungen", "Wii Remote connections"); A("Bluetooth", "Bluetooth");
        A("Keine Wii Remote verbunden.", "No Wii Remote connected.");
        A("In Mode 1–3 kann der Hub die Wii Remotes nicht direkt sehen – erst Mode 4 zeigt Slots, Batterie und Spieler.", "In modes 1–3 the hub cannot see the Wii Remotes directly – only mode 4 shows slots, battery and players.");
        A("Wii-Spiele: freie Spielerplätze mit echten Wii Remotes belegen", "Wii games: fill free player slots with real Wii Remotes");
        A("Die Wii Remotes werden hier als Controller geführt – ihren Spieler tauschst du oben in den Spieler-Karten.", "The Wii Remotes are listed here as controllers – change their player in the player cards above.");
        A("Die LED an der Wii Remote zeigt schon jetzt ihren Spieler.", "The LED on the Wii Remote already shows its player.");
        A("Alle 4 Spielerplätze sind von anderen Controllern bzw. der Tastatur belegt – Wii Remotes werden nicht verwendet.", "All 4 player slots are taken by other controllers or the keyboard – Wii Remotes are not used.");
        A("Tastatur in Spielen: Aus", "Keyboard in games: Off");
        A("Aus: Wii-Spiele nutzen nur die oben zugewiesenen Controller.", "Off: Wii games only use the controllers assigned above.");
        A("Sensortest", "Sensor test"); A("Test beenden", "Stop test");
        A("Prüft Sensorleiste, Zeiger, Tasten und Neigung live mit der Kamera der Wii Remote. Dolphin darf dabei nicht laufen.", "Checks sensor bar, pointer, buttons and tilt live with the Wii Remote's camera. Dolphin must not be running.");
        A("Für den Sensortest die DolphinBar auf Mode 4 stellen und eine Wii Remote verbinden (1+2).", "For the sensor test set the DolphinBar to mode 4 and connect a Wii Remote (1+2).");
        A("Verbinde zuerst eine Wii Remote (DolphinBar Mode 4: an der Wii Remote 1+2 drücken).", "Connect a Wii Remote first (DolphinBar mode 4: press 1+2 on the Wii Remote).");
        A("Die Wii-Systemeinstellungen von Dolphin fehlen noch – einmal ein Wii-Spiel starten, dann sind sie hier einstellbar.", "Dolphin's Wii system settings are missing – start a Wii game once, then they can be set here.");
        A("Position der Sensorleiste", "Sensor bar position"); A("Über dem Bildschirm", "Above the screen"); A("Unter dem Bildschirm", "Below the screen");
        A("Empfindlichkeit (1 = gering … 5 = hoch). Zittert oder springt der Zeiger: niedriger. Verliert er die Leiste aus großer Entfernung: höher.", "Sensitivity (1 = low … 5 = high). If the pointer jitters or jumps: lower. If it loses the bar from a distance: higher.");
        A("3 (Standard)", "3 (default)"); A("Vibration der Wii Remote", "Wii Remote rumble");
        A("Lautsprecher der Wii Remote (kann auf manchen PCs ruckeln)", "Wii Remote speaker (may stutter on some PCs)"); A("Lautstärke", "Volume");
        A("Gilt für alle Wii-Spiele in Dolphin (Wii-Systemeinstellungen). Dolphin muss beim Ändern geschlossen sein.", "Applies to all Wii games in Dolphin (Wii system settings). Dolphin must be closed when changing this.");
        A("Sensorleiste & Wii Remote – Einstellungen", "Sensor bar & Wii Remote – settings");
        A("leer – an der Wii Remote 1+2 drücken", "empty – press 1+2 on the Wii Remote"); A("kein Spieler (LEDs aus)", "no player (LEDs off)");
        A("kein Spieler zugewiesen", "no player assigned"); A(" · Bluetooth", " · Bluetooth"); A("Erweiterung: ", "Extension: ");
        A("antwortet nicht", "not responding");
        A("Sensortest nicht möglich, solange Dolphin läuft (Dolphin hat die Wii Remotes).", "Sensor test not possible while Dolphin is running (Dolphin has the Wii Remotes).");
        A("Wii-Einstellungen konnten nicht gelesen werden", "Wii settings could not be read");
        A("Gespeichert ✓ – gilt ab dem nächsten Start eines Wii-Spiels.", "Saved ✓ – applies from the next Wii game launch."); A("Speichern fehlgeschlagen: ", "Saving failed: ");
        A("DolphinBar Mode 4", "DolphinBar mode 4"); A("DolphinBar auf Mode 3 – bitte Mode 4", "DolphinBar on mode 3 – please use mode 4");
        A("DolphinBar auf Mode 1/2 – bitte Mode 4", "DolphinBar on mode 1/2 – please use mode 4"); A("Keine DolphinBar", "No DolphinBar");
        A("Tastatur aus", "Keyboard off"); A("Tastatur automatisch", "Keyboard automatic"); A("PadForge bereit", "PadForge ready");
        A("PadForge nicht installiert", "PadForge not installed");
        A("Wii-Spiele: Tastatur hat Vorrang – Wii Remote rückt auf den nächsten freien Platz", "Wii games: keyboard takes priority – the Wii Remote moves to the next free slot");
        A("in Wii-Spielen (Dolphin)", "in Wii games (Dolphin)"); A("Kabel", "Wired"); A("Kabellos", "Wireless"); A("Akku unbekannt", "Battery unknown");
        A("PadForge läuft immer mit Administratorrechten – Windows fragt gleich einmal nach (UAC).\n\n", "PadForge always runs with administrator rights – Windows will ask once (UAC).\n\n");
        A("Beim ersten Start installiert PadForge den Treiber HIDMaestro für virtuelle Controller. Danach startet der Hub ", "On first start PadForge installs the HIDMaestro driver for virtual controllers. After that the hub starts ");
        A("PadForge bei Bedarf automatisch im Hintergrund und schaltet die Profile selbst um.\n\nJetzt starten?", "PadForge automatically in the background when needed and switches the profiles itself.\n\nStart now?");
        A("PadForge wird gestartet …", "Starting PadForge …");
        A("PadForge läuft und ist mit dem Hub verbunden ✓ Weise dort einmal deine Controller einem virtuellen Xbox-Slot zu (Add Controller).", "PadForge is running and connected to the hub ✓ Assign your controllers to a virtual Xbox slot there once (Add Controller).");
        A("PadForge antwortet noch nicht. Falls ein Fenster offen ist: Ersteinrichtung abschließen und unter Profiles „Allow External Control“ einschalten.", "PadForge is not responding yet. If a window is open: finish the initial setup and enable “Allow External Control” under Profiles.");
    }
}
